### ISSUE TITLE
Start on mockup

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/IHCC#13]
One of the main deliverables for this project is an OWL file that can be loaded into Overture and drive a faceted search interface similar to this:

https://hcmi-searchable-catalog.nci.nih.gov

There should be three primary facets (on the left), with one level of children:

- Clinical Finding (e.g. phenotype, disease)
- Measurement (e.g. assay)
- Exposure Event

The table at the bottom should show matching fields from the various data dictionaries with:

- data dictionary name and link
- matched field
- definition
- question
- harmonized ontology term

(This is a preliminary list that we'll have to revise.)

In order to ensure good communication and reduce risk, we're going to build a mockup of this interface starting now. It will be a single HTML file, loading a JSON file that defines the facets and data dictionaries, and using a bit of JavaScript to drive the interface. Once we have the basics of the interface working, we will figure out how to build the right OWL to generate the right JSON to make the mockup actually work. Then we can point to a working system, and coordinate with the Overture team on any revisions they require.

**Comment by beckyjackson** [comment]
> There should be three primary facets (on the left), with one level of children

Can we output GECKO organized this way, or do we need to process this somewhere else? Right now there's not much organization.

**Comment by jamesaoverton** [comment]
@beckyjackson Let's get the stuff you showed on Friday in to a PR.

**Comment by jamesaoverton** [comment]
Closed by #20
