### ISSUE TITLE
Covert KoGES to OWL

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/IHCC#16]
The Korean Genome and Epidemiology Study (KoGES) - The study is a consortium project consisting of six prospective cohort studies that would be categorized into population-based and gene-environment model studies (public and no licence).

http://www.cdc.go.kr/contents.es?mid=a50401010100

- [x] store `.tsv` or `.xlsx` in `data/`
- [x] update `data/README.md`
- [x] write Python conversion script
- [x] create `metadata/` TTL
- [x] update `Makefile` to build OWL

**Comment by beckyjackson** [comment]
This is done, but I'm going to wait on #26 before making the PR.
