### ISSUE TITLE
Extract NCIT module based on data/cineca.tsv

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/IHCC#2]
The `data/cineca.tsv` file has NCIT term IDs for most rows. We want to extract a subset of NCIT for those terms, then compare that hierarchy to the asserted hierarchy in `data/cineca.tsv`.

MIREOT extraction should be fine for now. Since the NCIT OWL file is biggish, it would be nice to use the new MIREOT-RDFXML code from https://github.com/ontodev/robot/pull/605. (It might have fancy nested OWL annotations that would exercise the edge cases we discussed, but we don't need to get those 100% correct for this purpose.)

**Comment by mcourtot** [comment]
As mentioned by email, the NCIT mappings are medium-trustable. There may be better terms available in other resources. I'm hoping we'll be able to run mapping tools eg OxO to generate the list of mappings as cross-refs for each term.

**Comment by jamesaoverton** [comment]
That's fine. I updated the demo site with new versions of the trees we've got so far.
