### ISSUE TITLE
Mockup browser down?

### ISSUE THREAD

**Issue by mcourtot** [jamesaoverton/IHCC#28]
https://ihcc.ontodev.com/branches/master/views/build/browser/index.html returns FileNotFoundError: [Errno 2] No such file or directory: '/var/www/ihcc.ontodev.com/workspace/master/build/browser/index.html'

**Comment by jamesaoverton** [comment]
Sorry! I fixed that.

That's the older browser demo. The newer version is here: https://ihcc.ontodev.com/branches/master/views/build/index.html
