### ISSUE TITLE
Create simple summary page for each cohort

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/IHCC#35]
Using the data we're collecting for #32 (and #29), I'd like a simple summary page for each cohort that we're showing in the mockup browser. The page should include that cohort data, and when available:

- link to the data dictionary document (preferably the original, otherwise our copy in GitHub)
- link to GECKO mapping sheet for that cohort
- link to the trees and OWL files we're building

These links are already in the Makefile for most things, but that's getting crowded.

These pages should really be simple -- nothing fancy required. They should go in the `build/` directory.

The cohort links in the first column of the mockup results table should be changed to point to these new pages.

**Comment by beckyjackson** [comment]
Here's what I have so far for the mockup -
![image](https://user-images.githubusercontent.com/16750150/79048041-32dccf80-7bcf-11ea-8ec2-86361c479d53.png)

Do we want to add more to it?

**Comment by jamesaoverton** [comment]
That’s great.
