### ISSUE TITLE
Generate OWL for Genomics England

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/IHCC#8]
Similar to #1 and #5, but bigger.

@mcourtot Can you please confirm that we're working with their v6.0? I see newer versions here, but they appear to be drafts:

https://cnfl.extge.co.uk/display/GERE/Main+Programme+Data+Releases

- [x] Copy <https://cnfl.extge.co.uk/download/attachments/113189195/Data%20Dictionary%20Main%20Programme%20v6%20%281%29.xlsx?version=1&modificationDate=1551371214157&api=v2&download=true> to `data/genomics-england.xlsx`
- [x] Update `data/README.md`
- [x] Create `src/genomics-england.py` script to generate a basic `build/genomics-england.tsv` ROBOT template; we don't care about the first six sheets, just 'APC' and following; I still think we want just one big ROBOT template; let's try to use the "Field" column for the term ID
- [x] Create `metadata/genomics-england.ttl` -- I'm not sure about the license
- [x] Update `Makefile` to build `build/genomics-england.owl` from the template and metadata

**Comment by beckyjackson** [comment]
Do we want these fields to be classes or properties (or we could have both?)?
Additionally, should we be parsing the values field to make instances?

**Comment by jamesaoverton** [comment]
Didn't mean to close this!

**Comment by jamesaoverton** [comment]
Pleas try to do this one like the others (rows become classes, columns are annotation properties), and we'll see what we've got.

**Comment by jamesaoverton** [comment]
I'll count this as closed by #10, and we'll create new issues for revisions.
